### ISSUE TITLE
"Thinking in human time is always a trap" is not true

### ISSUE THREAD

**Issue by malaire** [elm-lang/time#10]
README.md includes several incorrect statements, like:
"human time should basically never be stored in your Model or database"
"there are always exceptions where a recurring event gets moved"
"Thinking in human time is always a trap".

These are not true. For example if I want an app which gives notification on my birthday, ignoring timezones, and without exceptions, then only way to model that is to save (Month, DateOfMonth) in Model, i.e. the "human time".

**Comment by evancz** [comment]
I am using "human time" to talk about abstractions like `CivicTime` that claim to cover everything.

Storing a month and day in your model is reasonable. That's the point of [this section](https://github.com/elm/time#recurring-events).

I'll see if other people find this confusing, but in the meantime, I think it makes sense to keep it the same because I have not heard this particular sentiment from others.
